import Foundation

// MARK: - Datos del Metro

let lineas: [String: [String]] = [
    "Línea 1": [
        "Villa El Salvador",
        "Parque Industrial",
        "Pumacahua",
        "Villa María",
        "María Auxiliadora",
        "San Juan",
        "Atocongo",
        "Jorge Chávez",
        "Ayacucho",
        "Los Cabitos",
        "Angamos",
        "San Borja Sur",
        "La Cultura",
        "Nicolás Arriola",
        "Gamarra",
        "Miguel Grau",
        "El Ángel",
        "Presbítero Maestro",
        "Caja de Agua",
        "Pirámide del Sol",
        "Los Jardines",
        "Los Postes",
        "San Carlos",
        "San Martín",
        "Santa Rosa",
        "Bayóvar"
    ],
    "Línea 2": [
        "Puerto del Callao",
        "Buenos Aires",
        "Juan Pablo II",
        "Insurgentes",
        "Carmen de la Legua",
        "Óscar Benavides",
        "San Marcos",
        "Elio",
        "La Alborada",
        "Tingo María",
        "Parque Murillo",
        "Plaza Bolognesi",
        "Estación Central",
        "Plaza Manco Cápac",
        "Cangallo",
        "28 de Julio",
        "Nicolás Ayllón",
        "Circunvalación",
        "San Juan de Dios",
        "Evitamiento",
        "Óvalo Santa Anita",
        "Colectora Industrial",
        "Hermilio Valdizán",
        "Mercado Santa Anita",
        "Vista Alegre",
        "Prolongación Javier Prado",
        "Municipalidad de Ate"
    ],
    "Línea 3": [
        "El Álamo",
        "Huandoy",
        "2 de Octubre",
        "Villa Sol",
        "Naranjal",
        "Carlos Izaguirre",
        "Tomás Valle",
        "Bartolomé de las Casas",
        "José Granda",
        "Caquetá",
        "Tacna",
        "Garcilaso de la Vega",
        "Estación Central",
        "Parque de la Reserva",
        "Museo de Historia Natural",
        "César Canevaro",
        "Conde de San Isidro",
        "Andrés Aramburú",
        "Huaca Pucllana",
        "Parque Central de Miraflores",
        "Parque Reducto",
        "República de Panamá",
        "Juana Alarco",
        "Cabitos",
        "Alejandro Velasco",
        "Las Gardenias",
        "Los Héroes",
        "Pedro Miotta"
    ],
    "Línea 4": [
        "Gambetta",
        "Canta Callao",
        "Bocanegra",
        "Aeropuerto",
        "El Olivar",
        "Quilca",
        "Morales Duárez",
        "Carmen de la Legua",
        "Venezuela",
        "Rafael Escardó",
        "Pando",
        "José de Sucre",
        "Brasil",
        "Felipe Salaverry",
        "Guillermo Prescott",
        "Las Palmeras",
        "Conde de San Isidro",
        "Javier Prado",
        "Pablo Carriquirry",
        "La Cultura",
        "San Luis",
        "Monterrico",
        "Manuel Olguin",
        "Los Frutales",
        "La Molina",
        "Santa Patricia",
        "Mayorazgo",
        "Mercado Santa Anita"
    ]
]

func normalizar(_ texto: String) -> String {
    return texto
        .trimmingCharacters(in: .whitespacesAndNewlines)
        .folding(options: .diacriticInsensitive, locale: .current)
        .lowercased()
}
